env:
  - RAILS_VERSION=none
  - RAILS_VERSION=3.2
  - RAILS_VERSION=4.0
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  email:
    - sysadmin@cramerdev.com

